# Generated by Django 4.2.11 on 2024-06-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('mailid', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
