# Generated by Django 4.2.11 on 2024-06-18 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_administration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='appoinmenttime',
            field=models.TimeField(default=datetime.datetime(2024, 6, 18, 20, 39, 44, 717440, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
