# Generated by Django 4.2.11 on 2024-06-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_patientdetails_appoinmenttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='appoinmenttime',
            new_name='appointmenttime',
        ),
    ]
