# Generated by Django 4.2.11 on 2024-06-22 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_appoinmenttime_patientdetails_appointmenttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='phnumber',
        ),
        migrations.AddField(
            model_name='reviews',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
