# Generated by Django 4.2.11 on 2024-06-22 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reviews_phnumber_reviews_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='phoneno',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
