# Generated by Django 4.2.11 on 2024-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mailid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
