# Generated by Django 4.2.11 on 2024-06-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_review_mailid_alter_review_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
    ]
