# Generated by Django 4.2.11 on 2024-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_review_mailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mailid',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='review',
            name='phoneno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
