# Generated by Django 4.2.11 on 2024-06-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_review_mailid_remove_review_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mailid',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='phoneno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='servicetype',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
