# Generated by Django 4.2.11 on 2024-07-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_title', models.CharField(max_length=100)),
                ('des_type', models.BooleanField()),
                ('des_content', models.TextField()),
                ('des_img', models.ImageField(default=None, upload_to='Description_images')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagedetails')),
            ],
        ),
    ]
