# Generated by Django 4.2.11 on 2024-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_packagedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedescription',
            name='des_img',
            field=models.ImageField(blank=True, upload_to='Description_images'),
        ),
    ]
