# Generated by Django 4.2.11 on 2024-08-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_packagedescription_des_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
