# Generated by Django 4.2.11 on 2024-08-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='servicetype',
            new_name='gender',
        ),
    ]
