# Generated by Django 4.2.11 on 2024-08-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_beforeafterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeafterimage',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagedetails'),
        ),
    ]
