# Generated by Django 4.2.11 on 2024-08-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_beforeafterimage_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeafterimage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
