# Generated by Django 4.2.11 on 2024-08-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_beforeafterimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetails',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='title2',
        ),
    ]
